import json

# Initialize the dictionary with key-value pairs
dict = {
    "_APdf": "/Users/Kyle/Teaching/Assets/Software/AdobeAcrobat",
    "_AAep": "/Users/Kyle/Teaching/Assets/Software/AdobeAfterEffects",
    "_DAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Documentation_Ai",
    "_AAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Actions_Ai",
    "_BAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Brushes_Ai",
    "_LAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/LaserReady_Ai",
    "_MAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Mockup_Ai",
    "_OAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Objects_Ai",
    "_PAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Patterns_Ai",
    "_SAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Swatches_Ai",
    "_TAi": "/Users/Kyle/Teaching/Assets/Software/AdobeIllustrator/Templates_Ai",
    "_TIndd": "/Users/Kyle/Teaching/Assets/Software/AdobeInDesign/Temp_Indd",
    "_DIndd": "/Users/Kyle/Teaching/Assets/Software/AdobeInDesign",
    "_DLrC": "/Users/Kyle/Teaching/Assets/Software/AdobeLightroom",
    "_DEncd": "/Users/Kyle/Teaching/Assets/Software/AdobeMediaEncoder",
    "_DPsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Documentation_Psd",
    "_APsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Actions_Psd",
    "_BPsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Brushes_Psd",
    "_MPsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Mockups_Psd",
    "_ObPsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Objects_Psd",
    "_OvPsd": "/Users/Kyle/Teaching/Assets/Software/AdobePhotoshop/Overlays_Psd",
    "_DPPro": "/Users/Kyle/Teaching/Assets/Software/AdobePremierePro",
    "_DXd": "/Users/Kyle/Teaching/Assets/Software/AdobeXD",
    "_Canva": "/Users/Kyle/Teaching/Assets/Software/Canva",
    "_DCode": "/Users/Kyle/Teaching/Assets/Software/CodeLearning",
    "_DCss": "/Users/Kyle/Teaching/Assets/Software/Css",
    "_Boot": "/Users/Kyle/Teaching/Assets/Software/Css/Bootstrap_Css",
    "_DFig": "/Users/Kyle/Teaching/Assets/Software/Figma",
    "_TFig": "/Users/Kyle/Teaching/Assets/Software/Figma/Templates_Fig",
    "_FExt": "/Users/Kyle/Teaching/Assets/Software/FileExtensions",
    "_FMgmt": "/Users/Kyle/Teaching/Assets/Software/FileManagement",
    "_ScrptF": "/Users/Kyle/Teaching/Assets/Software/Font/Artistic_Fonts",
    "_Serif": "/Users/Kyle/Teaching/Assets/Software/Font/Serif_Fonts",
    "_Sans": "/Users/Kyle/Teaching/Assets/Software/Font/SansSerif_Fonts",
    "_GDoc": "/Users/Kyle/Teaching/Assets/Software/GoogleDocs",
    "_GMap": "/Users/Kyle/Teaching/Assets/Software/GoogleMaps",
    "_GSlide": "/Users/Kyle/Teaching/Assets/Software/GoogleSlides",
    "_GDrive": "/Users/Kyle/Teaching/Assets/Software/GoogleDrive",
    "_DHtml": "/Users/Kyle/Teaching/Assets/Software/HTML",
    "_Link": "/Users/Kyle/Teaching/Assets/Software/LinkedIn",
    "_Lottie": "/Users/Kyle/Teaching/Assets/Software/Lottie",
    "_Lunacy": "/Users/Kyle/Teaching/Assets/Software/Lunacy",
    "_DPptx": "/Users/Kyle/Teaching/Assets/Software/MicrosoftPowerPoint",
    "_TPptx": "/Users/Kyle/Teaching/Assets/Software/MicrosoftPowerPoint/Templates_Pptx",
    "_DDocx": "/Users/Kyle/Teaching/Assets/Software/MicrosoftWord",
    "_TDocx": "/Users/Kyle/Teaching/Assets/Software/MicrosoftWord/Templates_Docx",
    "_DNumb": "/Users/Kyle/Teaching/Assets/Software/Numbers",
    "_LinOs": "/Users/Kyle/Teaching/Assets/Software/Linux_Os",
    "_MacOs": "/Users/Kyle/Teaching/Assets/Software/Mac_Os",
    "_WinOs": "/Users/Kyle/Teaching/Assets/Software/Windows_Os",
    "_ProC": "/Users/Kyle/Teaching/Assets/Software/Procreate",
    "_YtDlp": "/Users/Kyle/Teaching/Assets/Software/VideoDownloadingApp",
    "_Lib": "/Users/Kyle/Teaching/Assets/References",
    "_BRef": "/Users/Kyle/Teaching/Assets/References/BrandStyleGuides_Ref",
    "_CRef": "/Users/Kyle/Teaching/Assets/References/Character_Ref",
    "_LRef": "/Users/Kyle/Teaching/Assets/References/Logos_Ref",
    "_TxtRef": "/Users/Kyle/Teaching/Assets/Reading/Texts",
    "_PresRef": "/Users/Kyle/Teaching/Assets/Presentations",
    "_Notes": "/Users/Kyle/Teaching/Assets/Reading/Read_Notes",
    "_TBook": "/Users/Kyle/Teaching/Assets/Reading/Textbooks",
    "_TWeb": "/Users/Kyle/Teaching/Assets/Reading/WebPDF",
    "_Hard": "/Users/Kyle/Teaching/Assets/Hardware",
    "_Dev": "/Users/Kyle/Teaching/Development",
    "_S2": "/Users/Kyle/Teaching/Courses/Sculpture2",
    "_S1": "/Users/Kyle/Teaching/Courses/Sculpture1",
    "_3DD": "/Users/Kyle/Teaching/Courses/3D",
    "_Clay": "/Users/Kyle/Teaching/Courses/Ceramics",
    "_Cur": "/Users/Kyle/Teaching/Courses/Curriculum",
    "_SS": "/Users/Kyle/Teaching/Courses/StudioSeminar",
    "_Syl" : "/Users/Kyle/Teaching/Courses/Syllabi",
    "_2D" : "/Users/Kyle/Teaching/Courses/2D"
}

# Convert the dictionary to JSON
json_dict = json.dumps(dict)
# Save the dictionary as a JSON file
with open("dict.json", "w") as file:
    json.dump(dict, file)
print(json_dict)